# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abdellah/Software/OSG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abdellah/Software/OSG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdellah/Software/OSG/CMakeFiles /home/abdellah/Software/OSG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdellah/Software/OSG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osgModel

# Build rule for target.
osgModel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgModel
.PHONY : osgModel

# fast build rule for target.
osgModel/fast:
	$(MAKE) -f CMakeFiles/osgModel.dir/build.make CMakeFiles/osgModel.dir/build
.PHONY : osgModel/fast

#=============================================================================
# Target rules for targets named osgVolume

# Build rule for target.
osgVolume: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgVolume
.PHONY : osgVolume

# fast build rule for target.
osgVolume/fast:
	$(MAKE) -f CMakeFiles/osgVolume.dir/build.make CMakeFiles/osgVolume.dir/build
.PHONY : osgVolume/fast

#=============================================================================
# Target rules for targets named runOSG

# Build rule for target.
runOSG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runOSG
.PHONY : runOSG

# fast build rule for target.
runOSG/fast:
	$(MAKE) -f CMakeFiles/runOSG.dir/build.make CMakeFiles/runOSG.dir/build
.PHONY : runOSG/fast

osgModel.o: osgModel.cpp.o
.PHONY : osgModel.o

# target to build an object file
osgModel.cpp.o:
	$(MAKE) -f CMakeFiles/osgModel.dir/build.make CMakeFiles/osgModel.dir/osgModel.cpp.o
.PHONY : osgModel.cpp.o

osgModel.i: osgModel.cpp.i
.PHONY : osgModel.i

# target to preprocess a source file
osgModel.cpp.i:
	$(MAKE) -f CMakeFiles/osgModel.dir/build.make CMakeFiles/osgModel.dir/osgModel.cpp.i
.PHONY : osgModel.cpp.i

osgModel.s: osgModel.cpp.s
.PHONY : osgModel.s

# target to generate assembly for a file
osgModel.cpp.s:
	$(MAKE) -f CMakeFiles/osgModel.dir/build.make CMakeFiles/osgModel.dir/osgModel.cpp.s
.PHONY : osgModel.cpp.s

osgVolume.o: osgVolume.cpp.o
.PHONY : osgVolume.o

# target to build an object file
osgVolume.cpp.o:
	$(MAKE) -f CMakeFiles/osgVolume.dir/build.make CMakeFiles/osgVolume.dir/osgVolume.cpp.o
.PHONY : osgVolume.cpp.o

osgVolume.i: osgVolume.cpp.i
.PHONY : osgVolume.i

# target to preprocess a source file
osgVolume.cpp.i:
	$(MAKE) -f CMakeFiles/osgVolume.dir/build.make CMakeFiles/osgVolume.dir/osgVolume.cpp.i
.PHONY : osgVolume.cpp.i

osgVolume.s: osgVolume.cpp.s
.PHONY : osgVolume.s

# target to generate assembly for a file
osgVolume.cpp.s:
	$(MAKE) -f CMakeFiles/osgVolume.dir/build.make CMakeFiles/osgVolume.dir/osgVolume.cpp.s
.PHONY : osgVolume.cpp.s

runOSG.o: runOSG.cpp.o
.PHONY : runOSG.o

# target to build an object file
runOSG.cpp.o:
	$(MAKE) -f CMakeFiles/runOSG.dir/build.make CMakeFiles/runOSG.dir/runOSG.cpp.o
.PHONY : runOSG.cpp.o

runOSG.i: runOSG.cpp.i
.PHONY : runOSG.i

# target to preprocess a source file
runOSG.cpp.i:
	$(MAKE) -f CMakeFiles/runOSG.dir/build.make CMakeFiles/runOSG.dir/runOSG.cpp.i
.PHONY : runOSG.cpp.i

runOSG.s: runOSG.cpp.s
.PHONY : runOSG.s

# target to generate assembly for a file
runOSG.cpp.s:
	$(MAKE) -f CMakeFiles/runOSG.dir/build.make CMakeFiles/runOSG.dir/runOSG.cpp.s
.PHONY : runOSG.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... osgModel"
	@echo "... osgVolume"
	@echo "... rebuild_cache"
	@echo "... runOSG"
	@echo "... osgModel.o"
	@echo "... osgModel.i"
	@echo "... osgModel.s"
	@echo "... osgVolume.o"
	@echo "... osgVolume.i"
	@echo "... osgVolume.s"
	@echo "... runOSG.o"
	@echo "... runOSG.i"
	@echo "... runOSG.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

